version: "3.8"

services:
  nginx-proxy:
    image: nginx:stable
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dvm_web
    restart: always

networks:
  dvm_web:
    name: dvm_web
    external: false
